# resources文件夹配置成资源文件可在.iml文件中直接配置，也可在File->Project Structure中配置
server:
  port: 8210
spring:
  datasource:
    url: jdbc:mysql://node1:3306/GM?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: node1:8848,node2:8848,node3:8848
#        namespace: dev

logging:
  level:
    root: INFO
  config: classpath:logback.xml

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

