# resources文件夹配置成资源文件可在.iml文件中直接配置，也可在File->Project Structure中配置
server:
  port: 8220
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: node1:8848,node2:8848,node3:8848
#        namespace: dev


