server:
  port: 8220
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: node1:8848,node2:8848,node3:8848
#        namespace: dev
zuul:
  routes:
    user-service: /gateway/user/**
    web-service: /gateway/web/**
#  ignored-patterns: /*-service/**


logging:
  level:
    com.netflix: debug
