# resources文件夹配置成资源文件可在.iml文件中直接配置，也可在File->Project Structure中配置
server:
  port: 8200
spring:
  datasource:
    url: jdbc:mysql://node3:3306/GM?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: web
  cloud:
    nacos:
      discovery:
        server-addr: node3:8848
#        namespace: dev

# 指定注册中心地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.169.7.20:8100/eureka/

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

